# Generated by Django 5.0.1 on 2024-02-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('caliber', models.IntegerField()),
                ('Producer', models.CharField(max_length=40)),
            ],
        ),
    ]
