# Generated by Django 5.0.1 on 2024-02-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_gun_caliber'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gun_images/'),
        ),
    ]
