# Generated by Django 5.0.1 on 2024-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_gun_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gun',
            old_name='type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='gun',
            old_name='Producer',
            new_name='producer',
        ),
        migrations.AddField(
            model_name='gun',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
