# Generated by Django 5.0.1 on 2024-02-06 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='guns',
        ),
        migrations.AddField(
            model_name='order',
            name='gun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Store.gun'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
