# Generated by Django 5.0.1 on 2024-02-06 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_rename_gun_order_guns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='guns',
            new_name='gun',
        ),
    ]
