# Generated by Django 5.0.1 on 2024-02-06 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_rename_gun_order_guns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guns',
        ),
        migrations.CreateModel(
            name='OrderGun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.gun')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='guns',
            field=models.ManyToManyField(through='Store.OrderGun', to='Store.gun'),
        ),
    ]
